### ISSUE TITLE
Problem with set default gw

### ISSUE THREAD

**Issue by giper45** [sspreitzer/shellinabox-container-image#2]
Hi, I have a configuration like this: 
```yaml
version: '2'
services:
  anotherShellina:
    image: 'sspreitzer/shellinabox '
    stdin_open: true
    tty: true
    ports:
      - '4200:4200'
    networks:
      network:
        ipv4_address: 192.168.1.4
    cap_add:
      - NET_ADMIN
  Jack:
    image: 'telnet_server:latest'
    stdin_open: true
    tty: true
    networks:
      anotherSubnet:
        ipv4_address: 192.168.2.2
    cap_add:
      - NET_ADMIN
  router:
    image: 'debian_base:latest'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 192.168.1.3
      anotherSubnet:
        ipv4_address: 192.168.2.3
    cap_add:
      - NET_ADMIN
networks:
  network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  anotherSubnet:
    ipam:
      config:
        - subnet: 192.168.2.1/24
```   
Just after docker-compose up I try to set the router programmatically by the following command: 
```
route add default gw router 
```
On other containers it works, but on shellinabox I cannot connect to localhost:4200... 
Anyway, if I try to change the route add with: 
```
ip route add 192.168.1.1 via 192.168.1.3 it works, can accesso to local networks and to http login
```    
Do you know why this ? Thanks !
